simulation:
  mode: "GUI" # HEADLESS or GUI
  time_step: 0.004166 # 1/240
  gravity: [0, 0, -9.8]
  max_steps: 800
  sleep: true # whether to use time.sleep

camera:
  width: 640
  height: 480
  fov: 90
  near: 0.1
  far: 100
  distance: 3.0
  yaw: 20
  pitch: -20

back_camera:
  width: 640
  height: 480
  fov: 90
  near: 0.1
  far: 100
  distance: 2.5
  yaw: 270
  pitch: -30
  roll: 0

car:
  urdf: "racecar/racecar.urdf"
  scale: 2.0
  position: [0, 0, 0.1]
  speed_profile: "NORMAL" # Options: SLOW, NORMAL, FAST, VERY_FAST
  wheel_joints: [2, 3, 5, 4]
  lateral_friction: 1.2
  spinning_friction: 0.02
  rolling_friction: 0.0

speed_profiles:
  SLOW:
    target_velocity: 60
    forward_force: 120
    description: "Slow and steady"
  NORMAL:
    target_velocity: 90
    forward_force: 220
    description: "Standard speed"
  FAST:
    target_velocity: 110
    forward_force: 250
    description: "High speed"
  VERY_FAST:
    target_velocity: 130
    forward_force: 280
    description: "Maximum speed"

cube:
  mass_ratio: 0.25 # cube_mass = car_mass * mass_ratio
  size_factor: 0.0375 # x times car scale
  position: [0.25, 0, 0.2]
  color: [0, 1, 0, 1]
  local_initial_pos: [0.25, 0, 0.2]
  limit_x: 0.25 # for PID pitch control

pid:
  kp: 6.0
  ki: 0.0
  kd: 0.6
  target_pitch: 0.0

world:
  plane_urdf: "plane.urdf"

ramp:
  length: 2.0
  width: 2.0
  thickness: 0.1
  angle_deg: 25
  angle_rad: 0.45 # if overriding radian angle
  position: [8, 0, 0.2]
  color: [0.8, 0.2, 0.2, 1]

logging:
  save_dir: "results/"
  video_file: "car_jump.mp4"
  video_fps: 30
  debug_text: true
