simulation:
  mode: "HEADLESS"           # HEADLESS or GUI
  time_step: 0.004166        # 1/240
  gravity: [0, 0, -9.8]
  max_steps: 800
  sleep: true                # whether to use time.sleep

camera:
  width: 640
  height: 480
  fov: 90
  near: 0.1
  far: 100
  distance: 4.0
  yaw: 20
  pitch: -20

car:
  urdf: "racecar/racecar.urdf"
  scale: 2.0
  position: [0, 0, 0.1]
  forward_force: 200.0
  target_velocity: 100
  wheel_joints: [2, 3, 5, 4]
  lateral_friction: 1.2
  spinning_friction: 0.02
  rolling_friction: 0.0

cube:
  mass_ratio: 0.25           # cube_mass = car_mass * mass_ratio
  size_factor: 0.0375                # x times car scale
  position: [0.25, 0, 0.2]
  color: [0, 1, 0, 1]
  local_initial_pos: [0.25, 0, 0.2]
  limit_x: 0.25        # for PID pitch control

pid:
  kp: 6.0
  ki: 0.0
  kd: 0.6
  target_pitch: 0.0

world:
  plane_urdf: "plane.urdf"

ramp:
  length: 2.0
  width: 2.0
  thickness: 0.1
  angle_deg: 25
  angle_rad: 0.45            # if overriding radian angle
  position: [8, 0, 0.2]
  color: [0.8, 0.2, 0.2, 1]

logging:
  save_dir: "results/"
  video_file: "car_jump.mp4"
  video_fps: 30
  debug_text: true